INSERT INTO coins
	(type, name, description, issuing_country, composition,
    quality, denomition, year, weight, price, first, second)
VALUES
	('exclusive','Lion sedge',
    'Indian coin with the image of a lion Ashoka. Face value 1 one rupee. 1975 edition.',
    'India','steel','BU','1 rupee',1975,'4.95 g','76$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\lion-sedge\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\lion-sedge\\2.png'),
	('exclusive','Rial',
    'Iranian silver coin with the image of a lion. Face value 5000 five thousand dinars (5 five taps). 1928 year.',
    'Iran','silver','BU','5000 dinars',1928,'6.12 g','98$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\rial\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\rial\\2.png'),
    ('exclusive','ISK',
    'Icelandic coin with a picture of a fish. Face value 1 Icelandic krona',
    'Iceland','nickel','BU','1 Icelandic krona',2007,'5.42 g','78$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\isk\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\isk\\2.png'),
    ('exclusive','',
    '',
    '','','','',0000,'','',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\2.png'),
    ('exclusive','',
    '',
    '','','','',0000,'','',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\2.png'),
    ('exclusive','',
    '',
    '','','','',0000,'','',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\2.png'),
    ('exclusive','',
    '',
    '','','','',0000,'','',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\2.png'),
    ('exclusive','',
    '',
    '','','','',0000,'','',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\2.png'),
    ('exclusive','',
    '',
    '','','','',0000,'','',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\2.png'),
    ('exclusive','',
    '',
    '','','','',0000,'','',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\2.png'),
    ('exclusive','',
    '',
    '','','','',0000,'','',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\2.png'),
    ('exclusive','',
    '',
    '','','','',0000,'','',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\2.png'),
    ('exclusive','',
    '',
    '','','','',0000,'','',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\\\2.png'),