INSERT INTO coins
	(type, name, description, issuing_country, composition,
    quality, denomition, year, weight, price, first, second)
VALUES
	('bullion','South Vietnamese Dong',
    'Currency of the Republic of Vietnam in 1955-1975 Coin with the image of wheat.',
    'the Republic of Vietnam','nickel','BU','1 dong',1955,'5.05 g','56$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\south-vietnamese-dong\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\south-vietnamese-dong\\2.png'),
    ('bullion','The British Antelope',
    'Unique coin depicting an antelope. British South African gold coin with a face value of 1/2 pound. It has been produced since 1952.',
    'British South Africa','gold','BU','1/2 pound',1952,'6.3 g','78$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\the-british-antelope\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\the-british-antelope\\2.png'),
    ('bullion','Cron',
    'A unique coin depicting a Knorr Viking ship at sea.',
    'Estonia','gold','BU','1/2 pound',1934,'5.67 g','79$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\cron\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\cron\\2.png'),
    ('bullion','Franc',
    'Unique coin with the image of a walking elephant. "Frank" of the Belgian Congo.',
    'the Belgian Congo','gold','BU','2 francs',1947,'5.45 g','68$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\franc\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\franc\\2.png'),
    ('bullion','Stork',
    'Unique coin with the image of a flying stork. French coin at 2 two francs 1997.',
    'France','steel','BU','2 francs',1997,'6.57 g','54$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\stork\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\stork\\2.png'),
    ('bullion','Gyeonggi',
    '"Gyeonggi". Coin with the image of five kangaroos - symbols of Australia.',
    'Australia','gold','BU','1 dolla',1984,'4.76 g','97$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\gyeonggi\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\gyeonggi\\2.png'),
    ('bullion','Bolivian Peso',
    'Boliviano Coin with the image of Bolivia.',
    'Bolivia','steel','BU','1 PESO',1988,'3.62 g','54$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\bolivian-peso\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\bolivian-peso\\2.png'),
    ('bullion','Botswana',
    '"Botswana". Coin with the image of a bird.',
    'Botswana','steel','BU','1 thebe',1976,'4.28 g','62$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\boltswana\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\boltswana\\2.png'),
    ('bullion','Virginia',
    'Virginia Coin with the image of a seahorse. Coin created during the reign of Elizabeth II.',
    'British Virgin Islands','nickel','BU','5 dollars',2014,'6.98 g','108$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\virginia\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\virginia\\2.png'),
    ('bullion','Theobroma Cocoa',
    'Coin with a lion in the center of the shield. Ghana coin, published in 1967.',
    'Ghana','steel','BU','20 pesewas',1962,'4.76 g','54$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\theobroma-cocoa\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\theobroma-cocoa\\2.png'),
    ('bullion','Coin of the Weimar Republic',
    'The Hindenburg Coin with the coat of arms of the Weimar Republic.',
    'the Weimar Republic','silver','BU','5 Mark',1927,'4.76 g','142$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\coin-of-the-weimar-republic\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\coin-of-the-weimar-republic\\2.png'),
    ('bullion','Scientist',
    'Silver Egyptian coin with the image of the god Thoth. Silver Egyptian coin.',
    'Egypt','silver','BU','1 pound',1981,'3.95 g','112$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\scientist\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\scientist\\2.png');