INSERT INTO coins
	(type, name, description, issuing_country, composition,
    quality, denomition, year, weight, price, first, second)
VALUES
	('commemorative','Canadian Beaver',
    '"Canadian beaver". Unique coin with the image of a beaver. Face value - 5 cents. Created under Elizabeth II.',
    'CANADA','nickel','BU','5 cents',1965,'4.54 g','40$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\canadian-beaver\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\canadian-beaver\\2.png'),
    ('commemorative','Looney',
    '"Looney". Unique coin with the image of a goat. Canadian dollar symbol.',
    'CANADA','gold','BU','1 dollar',1970,'5.4 g','65$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\looney\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\looney\\2.png'),
    ('commemorative','Jefferson',
    'Unique coin featuring Thomas Jefferson, the 3rd American president. Face value - 5 cents.',
    'UNITED STATES OF AMERICA','nickel','BU','5 cents',1966,'3.54 g','35$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\jefferson\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\jefferson\\2.png'),
    ('commemorative','Kennedy',
    'The unique coin is made in honor of the assassination of the 35th president of Texas.',
    'UNITED STATES OF AMERICA','nickel','BU','HALF DOLLAR',1963,'4.3 g','43$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\kennedy\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\kennedy\\2.png'),
    ('commemorative','Canadian Cent',
    '"Canadian cent." A unique coin with the image of maple leaves - symbols of Canada. Face value - 1 cent.',
    'CANADA','Steel','BU','1 cent',1965,'2.7 g','8$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\canadian-cent\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\canadian-cent\\2.png'),
    ('commemorative','A penny',
    '"A penny". A unique coin with a shield image with 13 vertical stripes.',
    'UNITED STATES OF AMERICA','Steel','BU','1 cent',1793,'5.1 g','8$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\a-penny\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\a-penny\\2.png'),
    ('commemorative','25 cents',
    'Unique coin depicting a caribou (reindeer). The face value of the coin is equal to a quarter of the Canadian dollar.',
    'CANADA','nickel','BU','25 cents',1966,'5.7 g','80$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\25-cents\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\25-cents\\2.png'),
    ('commemorative','Dim Sum',
    'Dim Sum is a 10-cent coin of the United States that has been minted from 1946 to the present. This is a unique coin with the image of a torch, oak and olive branches.',
    'UNITED STATES OF AMERICA','nickel','BU','10 cents',1946,'4.25 g','10$',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\dim-sum\\1.png',
    'C:\\Users\\Administrator\\Desktop\\catalog-of-precious-coins\\coins\\src\\images\\dim-sum\\2.png');